<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'title'             => 'Guitarra eléctrica versátil',
                'subtitle'          => 'PRS SE 24-08 Standard Tobacco Sunburst',
                'description'       => 'Guitarra eléctrica de doble pastilla con cuerpo de caoba y mástil de arce. Ideal para rock, blues y metal.',
                'category'          => 'Instrumentos',
                'brand'             => 'PRS',
                'stock'             => 10,
                'price'             => 2474529,
                'installments'      => 3,
                'installment_price' => 769853.46,
                'on_sale'           => true,
                'discount'          => 15,
                'active'            => true,
                'image_1'           => 'products/images/guitarra-prs.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'PRS', 'Modelo' => 'SE 24-08', 'Conectividad' => 'Jack 6.35mm', 'Peso' => '3.5kg'],
            ],
            [
                'title'             => 'Guitarra electroacústica dreadnought con cutaway',
                'subtitle'          => 'Fender Redondo™ Player',
                'description'       => 'Guitarra electroacústica con tapa de abeto y sistema de pastilla integrado. Perfecta para tocar enchufada o acústica.',
                'category'          => 'Instrumentos',
                'brand'             => 'Fender',
                'stock'             => 5,
                'price'             => 858299,
                'installments'      => 3,
                'installment_price' => 286099,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/guitarra-fender.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Fender', 'Modelo' => 'Redondo Player', 'Conectividad' => 'Jack 6.35mm', 'Peso' => '2.8kg'],
            ],
            [
                'title'             => 'Guitarra eléctrica tipo Stratocaster',
                'subtitle'          => 'Benson HD 901 BK',
                'description'       => 'Guitarra eléctrica tipo Stratocaster con tres pastillas single-coil y cuerpo de tilo. Excelente para principiantes.',
                'category'          => 'Instrumentos',
                'brand'             => 'Benson',
                'stock'             => 8,
                'price'             => 609709,
                'installments'      => 3,
                'installment_price' => 182912.7,
                'on_sale'           => true,
                'discount'          => 10,
                'active'            => true,
                'image_1'           => 'products/images/guitarra-benson.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Benson', 'Modelo' => 'HD 901 BK', 'Conectividad' => 'Jack 6.35mm', 'Peso' => '3.2kg'],
            ],
            [
                'title'             => 'Guitarra acústica concierto',
                'subtitle'          => 'Cort AD810M Mahogany',
                'description'       => 'Guitarra acústica con cuerpo de caoba, ideal para estudiantes que buscan un sonido cálido y proyección equilibrada.',
                'category'          => 'Instrumentos',
                'brand'             => 'Cort',
                'stock'             => 12,
                'price'             => 368449,
                'installments'      => 3,
                'installment_price' => 122816,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/guitarra-cort.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Cort', 'Modelo' => 'AD810M', 'Conectividad' => 'No aplica', 'Peso' => '2.1kg'],
            ],
            [
                'title'             => 'Guitarra electroacústica dreadnought',
                'subtitle'          => 'Cort AD810E',
                'description'       => 'Guitarra electroacústica dreadnought con previo integrado y afinador incorporado. Lista para el escenario.',
                'category'          => 'Instrumentos',
                'brand'             => 'Cort',
                'stock'             => 7,
                'price'             => 406569,
                'installments'      => 3,
                'installment_price' => 135523,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/guitarra-cort.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Cort', 'Modelo' => 'AD810E', 'Conectividad' => 'Jack 6.35mm', 'Peso' => '2.3kg'],
            ],
            [
                'title'             => 'Guitarra eléctrica double cutaway',
                'subtitle'          => 'PRS SE Custom 24-08',
                'description'       => 'La PRS SE Custom 24-08 ofrece versatilidad tonal con sus pastillas de bobina dividida. Cuerpo de caoba con tapa de arce.',
                'category'          => 'Instrumentos',
                'brand'             => 'PRS',
                'stock'             => 4,
                'price'             => 3219129,
                'installments'      => 3,
                'installment_price' => 858434.4,
                'on_sale'           => true,
                'discount'          => 20,
                'active'            => true,
                'image_1'           => 'products/images/guitarra-prs.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'PRS', 'Modelo' => 'SE Custom 24-08', 'Conectividad' => 'Jack 6.35mm', 'Peso' => '3.6kg'],
            ],
            [
                'title'             => 'Piano digital compacto',
                'subtitle'          => 'Yamaha P-45',
                'description'       => 'Piano digital con 88 teclas contrapesadas y acción de martillo graduada. Sonido auténtico de cola Yamaha.',
                'category'          => 'Instrumentos',
                'brand'             => 'Yamaha',
                'stock'             => 6,
                'price'             => 1850000,
                'installments'      => 3,
                'installment_price' => 555000,
                'on_sale'           => true,
                'discount'          => 10,
                'active'            => true,
                'image_1'           => 'products/images/piano-yamaha.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Yamaha', 'Modelo' => 'P-45', 'Teclas' => '88', 'Conectividad' => 'USB, Jack 6.35mm', 'Peso' => '11.5kg'],
            ],
            [
                'title'             => 'Piano digital profesional',
                'subtitle'          => 'Casio Privia PX-160',
                'description'       => 'Piano digital con tecnología de teclado de acción de martillo tri-sensor. Ideal para pianistas exigentes.',
                'category'          => 'Instrumentos',
                'brand'             => 'Casio',
                'stock'             => 3,
                'price'             => 2100000,
                'installments'      => 3,
                'installment_price' => 700000,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/piano-casio.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Casio', 'Modelo' => 'Privia PX-160', 'Teclas' => '88', 'Conectividad' => 'USB, MIDI, Jack 6.35mm', 'Peso' => '10.8kg'],
            ],
            [
                'title'             => 'Clarinete Sib estudio',
                'subtitle'          => 'Yamaha YCL-255',
                'description'       => 'Clarinete en Sib ideal para estudiantes. Cuerpo de ABS resistente con llaves niqueladas de alta durabilidad.',
                'category'          => 'Instrumentos',
                'brand'             => 'Yamaha',
                'stock'             => 9,
                'price'             => 950000,
                'installments'      => 3,
                'installment_price' => 278666.66,
                'on_sale'           => true,
                'discount'          => 12,
                'active'            => true,
                'image_1'           => 'products/images/clarinete-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Yamaha', 'Modelo' => 'YCL-255', 'Tonalidad' => 'Sib', 'Material' => 'ABS', 'Peso' => '0.7kg'],
            ],
            [
                'title'             => 'Clarinete profesional',
                'subtitle'          => 'Buffet Crampon E11',
                'description'       => 'Clarinete profesional de madera grenadilla con mecanismo plateado. Respuesta precisa y timbre cálido en todos los registros.',
                'category'          => 'Instrumentos',
                'brand'             => 'Buffet',
                'stock'             => 2,
                'price'             => 1450000,
                'installments'      => 3,
                'installment_price' => 483333,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/clarinete-2.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Buffet Crampon', 'Modelo' => 'E11', 'Tonalidad' => 'Sib', 'Material' => 'Grenadilla', 'Peso' => '0.9kg'],
            ],
            [
                'title'             => 'Auriculares de estudio',
                'subtitle'          => 'Audio-Technica ATH-M20X',
                'description'       => 'Auriculares circumaurales cerrados para monitoreo de estudio. Respuesta de frecuencia extendida y graves profundos.',
                'category'          => 'Audio',
                'brand'             => 'Audio-Technica',
                'stock'             => 15,
                'price'             => 180000,
                'installments'      => 3,
                'installment_price' => 48000,
                'on_sale'           => true,
                'discount'          => 20,
                'active'            => true,
                'image_1'           => 'products/images/auricular-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Audio-Technica', 'Modelo' => 'ATH-M20X', 'Tipo' => 'Circumaural cerrado', 'Impedancia' => '47 Ohm', 'Peso' => '190g'],
            ],
            [
                'title'             => 'Auriculares profesionales',
                'subtitle'          => 'Sony MDR-7506',
                'description'       => 'Auriculares de referencia utilizados en estudios de grabación profesionales en todo el mundo. Plegables y livianos.',
                'category'          => 'Audio',
                'brand'             => 'Sony',
                'stock'             => 11,
                'price'             => 250000,
                'installments'      => 3,
                'installment_price' => 83333,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/auricular-2.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Sony', 'Modelo' => 'MDR-7506', 'Tipo' => 'Circumaural cerrado', 'Impedancia' => '63 Ohm', 'Peso' => '230g'],
            ],
            [
                'title'             => 'Atril plegable',
                'subtitle'          => 'Hamilton KB100',
                'description'       => 'Atril de música plegable y liviano, ideal para uso en casa o en giras. Regulable en altura y ángulo.',
                'category'          => 'Soportes',
                'brand'             => 'Hamilton',
                'stock'             => 20,
                'price'             => 45000,
                'installments'      => 3,
                'installment_price' => 14250,
                'on_sale'           => true,
                'discount'          => 5,
                'active'            => true,
                'image_1'           => 'products/images/atril-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Hamilton', 'Modelo' => 'KB100', 'Material' => 'Acero', 'Plegable' => 'Sí', 'Peso' => '0.9kg'],
            ],
            [
                'title'             => 'Atril reforzado',
                'subtitle'          => 'K&M 101',
                'description'       => 'Atril profesional de acero reforzado con bandeja amplia. Resistente y estable para partituras de gran formato.',
                'category'          => 'Soportes',
                'brand'             => 'K&M',
                'stock'             => 14,
                'price'             => 65000,
                'installments'      => 3,
                'installment_price' => 21666,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/atril-2.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'K&M', 'Modelo' => '101', 'Material' => 'Acero reforzado', 'Plegable' => 'Sí', 'Peso' => '1.4kg'],
            ],
            [
                'title'             => 'Flauta traversa estudio',
                'subtitle'          => 'Yamaha YFL-222',
                'description'       => 'Flauta traversa en Do para estudiantes. Cuerpo de alpaca plateado con mecanismo de llaves precisas y ergonómicas.',
                'category'          => 'Instrumentos',
                'brand'             => 'Yamaha',
                'stock'             => 6,
                'price'             => 780000,
                'installments'      => 3,
                'installment_price' => 239200,
                'on_sale'           => true,
                'discount'          => 8,
                'active'            => true,
                'image_1'           => 'products/images/flauta-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Yamaha', 'Modelo' => 'YFL-222', 'Tonalidad' => 'Do', 'Material' => 'Alpaca plateada', 'Peso' => '0.5kg'],
            ],
            [
                'title'             => 'Flauta traversa profesional',
                'subtitle'          => 'Gemeinhardt 2SP',
                'description'       => 'Flauta traversa plateada con cabeza de plata sólida. Respuesta rápida y timbre brillante para músicos avanzados.',
                'category'          => 'Instrumentos',
                'brand'             => 'Gemeinhardt',
                'stock'             => 3,
                'price'             => 1100000,
                'installments'      => 3,
                'installment_price' => 366666,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/flauta-2.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Gemeinhardt', 'Modelo' => '2SP', 'Tonalidad' => 'Do', 'Material' => 'Plata sólida', 'Peso' => '0.6kg'],
            ],
            [
                'title'             => 'Bajo eléctrico activo',
                'subtitle'          => 'Ibanez GSR200',
                'description'       => 'Bajo eléctrico con electrónica activa y ecualizador de 2 bandas. Cuerpo de tilo liviano con mástil de arce.',
                'category'          => 'Instrumentos',
                'brand'             => 'Ibanez',
                'stock'             => 7,
                'price'             => 890000,
                'installments'      => 3,
                'installment_price' => 252166.66,
                'on_sale'           => true,
                'discount'          => 15,
                'active'            => true,
                'image_1'           => 'products/images/bajo-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Ibanez', 'Modelo' => 'GSR200', 'Cuerdas' => '4', 'Conectividad' => 'Jack 6.35mm', 'Peso' => '3.4kg'],
            ],
            [
                'title'             => 'Bajo eléctrico clásico',
                'subtitle'          => 'Fender Precision Bass',
                'description'       => 'El Fender Precision Bass es el bajo eléctrico de referencia mundial. Sonido potente y definido, perfecto para cualquier género.',
                'category'          => 'Instrumentos',
                'brand'             => 'Fender',
                'stock'             => 4,
                'price'             => 1600000,
                'installments'      => 3,
                'installment_price' => 533333,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/bajo-2.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Fender', 'Modelo' => 'Precision Bass', 'Cuerdas' => '4', 'Conectividad' => 'Jack 6.35mm', 'Peso' => '4.1kg'],
            ],
            [
                'title'             => 'Micrófono dinámico',
                'subtitle'          => 'Shure SM58',
                'description'       => 'El micrófono vocal más popular del mundo. Patrón cardioide, filtro antipop integrado y construcción indestructible.',
                'category'          => 'Audio',
                'brand'             => 'Shure',
                'stock'             => 18,
                'price'             => 320000,
                'installments'      => 3,
                'installment_price' => 96000,
                'on_sale'           => true,
                'discount'          => 10,
                'active'            => true,
                'image_1'           => 'products/images/microfono-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Shure', 'Modelo' => 'SM58', 'Tipo' => 'Dinámico', 'Patrón' => 'Cardioide', 'Peso' => '298g'],
            ],
            [
                'title'             => 'Micrófono condensador',
                'subtitle'          => 'AKG P120',
                'description'       => 'Micrófono condensador de diafragma grande para grabación de voces e instrumentos acústicos en estudio.',
                'category'          => 'Audio',
                'brand'             => 'AKG',
                'stock'             => 9,
                'price'             => 210000,
                'installments'      => 3,
                'installment_price' => 70000,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/microfono-2.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'AKG', 'Modelo' => 'P120', 'Tipo' => 'Condensador', 'Patrón' => 'Cardioide', 'Peso' => '160g'],
            ],
            [
                'title'             => 'Teclado portátil',
                'subtitle'          => 'Casio CTK-3500',
                'description'       => 'Teclado portátil con 61 teclas, 400 tonos y ritmos integrados. Ideal para comenzar a estudiar música.',
                'category'          => 'Instrumentos',
                'brand'             => 'Casio',
                'stock'             => 13,
                'price'             => 480000,
                'installments'      => 3,
                'installment_price' => 131200,
                'on_sale'           => true,
                'discount'          => 18,
                'active'            => true,
                'image_1'           => 'products/images/teclado-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Casio', 'Modelo' => 'CTK-3500', 'Teclas' => '61', 'Conectividad' => 'USB, Jack 3.5mm', 'Peso' => '3.6kg'],
            ],
            [
                'title'             => 'Teclado profesional',
                'subtitle'          => 'Yamaha PSR-E373',
                'description'       => 'Teclado con 61 teclas sensitivas, 622 voces y función de lección integrada. Conexión USB y salida de auriculares.',
                'category'          => 'Instrumentos',
                'brand'             => 'Yamaha',
                'stock'             => 8,
                'price'             => 620000,
                'installments'      => 3,
                'installment_price' => 206666,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/teclado-2.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Yamaha', 'Modelo' => 'PSR-E373', 'Teclas' => '61', 'Conectividad' => 'USB, Jack 3.5mm', 'Peso' => '4.2kg'],
            ],
            [
                'title'             => 'Batería acústica completa',
                'subtitle'          => 'Pearl Export EXX',
                'description'       => 'Kit de batería acústica de 5 piezas con platillos incluidos. Cuerpos de álamo para un sonido potente y equilibrado.',
                'category'          => 'Instrumentos',
                'brand'             => 'Pearl',
                'stock'             => 3,
                'price'             => 3800000,
                'installments'      => 3,
                'installment_price' => 1114666.66,
                'on_sale'           => true,
                'discount'          => 12,
                'active'            => true,
                'image_1'           => 'products/images/guitarra-prs.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Pearl', 'Modelo' => 'Export EXX', 'Piezas' => '5', 'Material' => 'Álamo', 'Peso' => '45kg'],
            ],
            [
                'title'             => 'Batería electrónica',
                'subtitle'          => 'Roland TD-1DMK',
                'description'       => 'Batería electrónica silenciosa con pads de malla. Ideal para practicar en casa sin molestar a los vecinos.',
                'category'          => 'Instrumentos',
                'brand'             => 'Roland',
                'stock'             => 5,
                'price'             => 4200000,
                'installments'      => 3,
                'installment_price' => 1400000,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/piano-casio.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Roland', 'Modelo' => 'TD-1DMK', 'Piezas' => '5', 'Conectividad' => 'USB, Jack 6.35mm', 'Peso' => '22kg'],
            ],
            [
                'title'             => 'Violín de estudio',
                'subtitle'          => 'Stentor Student II 4/4',
                'description'       => 'Violín de tamaño completo para estudiantes con tapa de abeto sólido y costillas de arce. Incluye arco y estuche.',
                'category'          => 'Instrumentos',
                'brand'             => 'Stentor',
                'stock'             => 10,
                'price'             => 520000,
                'installments'      => 3,
                'installment_price' => 156000,
                'on_sale'           => true,
                'discount'          => 10,
                'active'            => true,
                'image_1'           => 'products/images/flauta-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Stentor', 'Modelo' => 'Student II', 'Tamaño' => '4/4', 'Material' => 'Abeto y arce', 'Peso' => '0.3kg'],
            ],
            [
                'title'             => 'Violín profesional',
                'subtitle'          => 'Yamaha V7SG 4/4',
                'description'       => 'Violín profesional con tapa de abeto sólido y costillas de arce flameado. Acabado brillante y sonido proyectado.',
                'category'          => 'Instrumentos',
                'brand'             => 'Yamaha',
                'stock'             => 4,
                'price'             => 980000,
                'installments'      => 3,
                'installment_price' => 326666,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/flauta-2.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Yamaha', 'Modelo' => 'V7SG', 'Tamaño' => '4/4', 'Material' => 'Abeto sólido y arce flameado', 'Peso' => '0.4kg'],
            ],
            [
                'title'             => 'Interface de audio USB',
                'subtitle'          => 'Focusrite Scarlett Solo 3ra Gen',
                'description'       => 'Interface de audio de 2 entradas y 2 salidas con previo de micrófono de alta calidad. Plug and play en Windows y Mac.',
                'category'          => 'Audio',
                'brand'             => 'Focusrite',
                'stock'             => 16,
                'price'             => 380000,
                'installments'      => 3,
                'installment_price' => 116533.33,
                'on_sale'           => true,
                'discount'          => 8,
                'active'            => true,
                'image_1'           => 'products/images/microfono-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Focusrite', 'Modelo' => 'Scarlett Solo 3ra Gen', 'Entradas' => '2', 'Conectividad' => 'USB-C', 'Peso' => '170g'],
            ],
            [
                'title'             => 'Soporte para guitarra',
                'subtitle'          => 'Hercules GS412B',
                'description'       => 'Soporte de guitarra con sistema de cierre automático. Compatible con guitarras eléctricas, acústicas y bajos.',
                'category'          => 'Soportes',
                'brand'             => 'Hercules',
                'stock'             => 22,
                'price'             => 58000,
                'installments'      => 3,
                'installment_price' => 19333,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/atril-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Hercules', 'Modelo' => 'GS412B', 'Material' => 'Acero y goma', 'Plegable' => 'Sí', 'Peso' => '0.8kg'],
            ],
            [
                'title'             => 'Cable de instrumento',
                'subtitle'          => 'Monster Standard 100',
                'description'       => 'Cable de instrumento de 3 metros con conectores de 6.35mm en ángulo recto. Blindado para eliminar el ruido.',
                'category'          => 'Accesorios',
                'brand'             => 'Monster',
                'stock'             => 30,
                'price'             => 18000,
                'installments'      => 3,
                'installment_price' => 5900,
                'on_sale'           => true,
                'discount'          => 5,
                'active'            => true,
                'image_1'           => 'products/images/atril-2.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Monster', 'Modelo' => 'Standard 100', 'Longitud' => '3m', 'Conectores' => 'Jack 6.35mm', 'Peso' => '150g'],
            ],
            [
                'title'             => 'Afinador cromático digital',
                'subtitle'          => 'Korg CA-50',
                'description'       => 'Afinador cromático para todos los instrumentos. Pantalla LCD con aguja analógica simulada y salida de sonido de referencia.',
                'category'          => 'Accesorios',
                'brand'             => 'Korg',
                'stock'             => 25,
                'price'             => 22000,
                'installments'      => 3,
                'installment_price' => 7333,
                'on_sale'           => false,
                'discount'          => 0,
                'active'            => true,
                'image_1'           => 'products/images/auricular-1.webp',
                'image_2'           => null,
                'image_3'           => null,
                'specs'             => ['Marca' => 'Korg', 'Modelo' => 'CA-50', 'Rango' => 'C1 - B7', 'Alimentación' => 'AAA x2', 'Peso' => '80g'],
            ],
        ];

        foreach ($products as $data) {

            // Busca la categoría o la crea si no existe
            $category = Category::firstOrCreate(
                ['name' => $data['category']],
                ['active' => true]
            );

            // Busca la marca o la crea si no existe
            $brand = Brand::firstOrCreate(
                ['name' => $data['brand']],
                ['active' => true]
            );

            // Crea el producto
            Product::create([
                'category_id'       => $category->id,
                'brand_id'          => $brand->id,
                'title'             => $data['title'],
                'subtitle'          => $data['subtitle'],
                'description'       => $data['description'],
                'stock'             => $data['stock'],
                'price'             => $data['price'],
                'installments'      => $data['installments'],
                'installment_price' => $data['installment_price'],
                'on_sale'           => $data['on_sale'],
                'discount'          => $data['discount'],
                'active'            => $data['active'],
                'specs'             => $data['specs'],
                'image_1'           => $data['image_1'],
                'image_2'           => $data['image_2'],
                'image_3'           => $data['image_3'],
            ]);
        }
    }
}
